version: "2"

services:
  postgresql:
    restart: always
    container_name: psql
    image: "postgres:latest"
    ports:
      - "5432:5432"
    #   volumes:
    #    - '/psql:/bitnami/postgresql'
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "POSTGRESQL_PASSWORD=1234"
      - "POSTGRESQL_DATABASE=postgres"
      - "POSTGRESQL_USERNAME=postgres"
volumes:
  postgresql_data:
    driver: local
