# Generated by Django 3.1 on 2020-08-12 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_category', models.CharField(choices=[('CONFERENCE', 'CONFERENCE'), ('SEMINAR', 'SEMINAR'), ('CONGRESS', 'CONGRESS'), ('COURSE', 'COURSE')], default='CONFERENCE', max_length=50)),
                ('event_place', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=100)),
                ('event_initial_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('VIRTUAL', 'VIRTUAL'), ('PRESENCIAL', 'PRESENCIAL')], max_length=30)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
            ],
        ),
    ]
